package com.sparrowpaul.greendaosample.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sparrowpaul.greendaosample.database.FavoriteQuote;

import com.sparrowpaul.greendaosample.database.FavoriteQuoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteQuoteDaoConfig;

    private final FavoriteQuoteDao favoriteQuoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteQuoteDaoConfig = daoConfigMap.get(FavoriteQuoteDao.class).clone();
        favoriteQuoteDaoConfig.initIdentityScope(type);

        favoriteQuoteDao = new FavoriteQuoteDao(favoriteQuoteDaoConfig, this);

        registerDao(FavoriteQuote.class, favoriteQuoteDao);
    }
    
    public void clear() {
        favoriteQuoteDaoConfig.clearIdentityScope();
    }

    public FavoriteQuoteDao getFavoriteQuoteDao() {
        return favoriteQuoteDao;
    }

}
